### ISSUE TITLE
Can't install matchmaker

### ISSUE THREAD

**Issue by RowanHarley** [rook2pawn/node-matchmaker#1]
I've been trying to install your matchmaker but I'm getting errors when I go to run it.
Here's the error:

`module.js:340
    throw err;
    ^

Error: Cannot find module 'partial'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Paula\Documents\node-matchmaker-0.1.0\index.js:3:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)`

**Comment by Astrydax** [comment]
its abandonware mate
